colors.draw_bold_text_with_bright_colors = true
#import = [ "~/.config/alacritty/catppuccin-mocha.yml" ]

# working_directory = "~/"
 [window]

opacity = 0.7

  [window.padding]
  x = 10
  y = 10

  [window.class]
  instance = "Alacritty"
  general = "Alacritty"

[scrolling]
history = 10_000
multiplier = 3

[font]
size = 7

  # [font.normal]
  # family = "JetBrainsMono Nerd Font"
  # style = "Regular"
  #
  # [font.bold]
  # family = "JetBrainsMono Nerd Font"
  # style = "Bold"
  #
  # [font.italic]
  # family = "JetBrainsMono Nerd Font"
  # style = "Italic"
  #
  # [font.bold_italic]
  # family = "JetBrainsMono Nerd Font"
  # style = "Bold Italic"

[selection]
save_to_clipboard = false

[terminal.shell]
program = "/usr/bin/zsh"

[[keyboard.bindings]]
key = "Return"
mods = "Super|Shift"
action = "SpawnNewInstance"

[terminal]
